// Shared interview metadata. AI requests are handled by the backend.
export const INTERVIEW_ROLES = [
  { value: 'ai_engineer', label: 'AI Engineer' },
  { value: 'generative_ai_engineer', label: 'Generative AI Engineer' },
  { value: 'machine_learning_engineer', label: 'Machine Learning Engineer' },
  { value: 'java_developer', label: 'Java Developer' },
  { value: 'python_developer', label: 'Python Developer' },
  { value: 'dotnet_developer', label: '.NET Developer' },
  { value: 'csharp_developer', label: 'C# Developer' },
  { value: 'nodejs_developer', label: 'Node.js Developer' },
  { value: 'react_developer', label: 'React Developer' },
  { value: 'angular_developer', label: 'Angular Developer' },
  { value: 'full_stack_developer', label: 'Full Stack Developer' },
  { value: 'backend_engineer', label: 'Backend Engineer' },
  { value: 'frontend_engineer', label: 'Frontend Engineer' },
  { value: 'data_scientist', label: 'Data Scientist' },
  { value: 'data_analyst', label: 'Data Analyst' },
  { value: 'data_engineer', label: 'Data Engineer' },
  { value: 'sql_developer', label: 'SQL Developer' },
  { value: 'business_analyst', label: 'Business Analyst' },
  { value: 'devops_engineer', label: 'DevOps Engineer' },
  { value: 'cloud_engineer', label: 'Cloud Engineer' },
  { value: 'aws_engineer', label: 'AWS Engineer' },
  { value: 'azure_engineer', label: 'Azure Engineer' },
  { value: 'cybersecurity_analyst', label: 'Cybersecurity Analyst' },
  { value: 'qa_automation_engineer', label: 'QA Automation Engineer' },
  { value: 'sdet', label: 'SDET' },
  { value: 'mobile_developer', label: 'Mobile Developer' },
  { value: 'software_architect', label: 'Software Architect' },
  { value: 'engineering_manager', label: 'Engineering Manager' },
  { value: 'product_manager', label: 'Product Manager' },
  { value: 'prompt_engineer', label: 'Prompt Engineer' },
  { value: 'ui_ux_designer', label: 'UI/UX Designer' },
  { value: 'hr_recruiter', label: 'HR / Recruiter' },
];

export const EXPERIENCE_LEVELS = [
  { value: 'fresher', label: 'Fresher' },
  { value: '1_3', label: '1-3 years' },
  { value: '3_5', label: '3-5 years' },
  { value: '5_7', label: '5-7 years' },
  { value: '7_10', label: '7-10 years' },
  { value: '10_12', label: '10-12 years' },
  { value: '12_15', label: '12-15 years' },
  { value: '15_20', label: '15-20 years' },
  { value: '20_25', label: '20-25 years' },
  { value: '25_30', label: '25-30 years' },
  { value: '30_35', label: '30-35 years' },
  { value: '35_plus', label: '35+ years' },
];

export const CAT_LABELS = {
  java_core: 'Java Core',
  oops: 'OOP',
  multithreading: 'Multithreading',
  spring: 'Spring Boot',
  microservices: 'Microservices',
  system_design: 'System Design',
  problem_solving: 'Problem Solving',
  behavioral: 'Behavioral',
  python_core: 'Python Core',
  django_fastapi: 'Django / FastAPI',
  data_modeling: 'Data Modeling',
  machine_learning: 'Machine Learning',
  ai_ml_systems: 'AI/ML Systems',
  generative_ai: 'Generative AI',
  llm_applications: 'LLM Applications',
  prompt_engineering: 'Prompt Engineering',
  rag: 'RAG',
  mlops: 'MLOps',
  model_evaluation: 'Model Evaluation',
  statistics: 'Statistics',
  sql: 'SQL',
  analytics: 'Analytics',
  business_intelligence: 'Business Intelligence',
  data_visualization: 'Data Visualization',
  query_optimization: 'Query Optimization',
  stored_procedures: 'Stored Procedures',
  requirements_analysis: 'Requirements Analysis',
  stakeholder_management: 'Stakeholder Management',
  process_modeling: 'Process Modeling',
  dotnet: '.NET',
  csharp: 'C#',
  nodejs: 'Node.js',
  async_programming: 'Async Programming',
  angular: 'Angular',
  rxjs: 'RxJS',
  react: 'React',
  javascript: 'JavaScript',
  frontend_architecture: 'Frontend Architecture',
  ux_research: 'UX Research',
  interaction_design: 'Interaction Design',
  design_systems: 'Design Systems',
  prototyping: 'Prototyping',
  api_design: 'API Design',
  databases: 'Databases',
  cloud_devops: 'Cloud / DevOps',
  aws: 'AWS',
  azure: 'Azure',
  iam: 'IAM',
  cloud_security: 'Cloud Security',
  networking: 'Networking',
  cost_optimization: 'Cost Optimization',
  security: 'Security',
  threat_detection: 'Threat Detection',
  incident_response: 'Incident Response',
  vulnerability_management: 'Vulnerability Management',
  testing: 'Testing',
  automation_frameworks: 'Automation Frameworks',
  api_testing: 'API Testing',
  quality_strategy: 'Quality Strategy',
  ci_cd: 'CI/CD',
  kubernetes: 'Kubernetes',
  observability: 'Observability',
  mobile_architecture: 'Mobile Architecture',
  leadership: 'Leadership',
  architecture: 'Architecture',
  people_management: 'People Management',
  hiring: 'Hiring',
  employee_relations: 'Employee Relations',
};

export const CAT_COLORS = {
  java_core: '#f59e0b',
  oops: '#ec4899',
  multithreading: '#10b981',
  spring: '#6366f1',
  microservices: '#06b6d4',
  system_design: '#3b82f6',
  problem_solving: '#a78bfa',
  behavioral: '#f97316',
  python_core: '#eab308',
  django_fastapi: '#22c55e',
  data_modeling: '#14b8a6',
  machine_learning: '#8b5cf6',
  ai_ml_systems: '#7c3aed',
  generative_ai: '#db2777',
  llm_applications: '#2563eb',
  prompt_engineering: '#9333ea',
  rag: '#4f46e5',
  mlops: '#0891b2',
  model_evaluation: '#ea580c',
  statistics: '#f43f5e',
  sql: '#0ea5e9',
  analytics: '#059669',
  business_intelligence: '#0284c7',
  data_visualization: '#0d9488',
  query_optimization: '#0369a1',
  stored_procedures: '#2563eb',
  requirements_analysis: '#ca8a04',
  stakeholder_management: '#f97316',
  process_modeling: '#65a30d',
  dotnet: '#512bd4',
  csharp: '#68217a',
  nodejs: '#22c55e',
  async_programming: '#16a34a',
  angular: '#dc2626',
  rxjs: '#c2185b',
  react: '#38bdf8',
  javascript: '#facc15',
  frontend_architecture: '#fb7185',
  ux_research: '#ec4899',
  interaction_design: '#f59e0b',
  design_systems: '#6366f1',
  prototyping: '#14b8a6',
  api_design: '#60a5fa',
  databases: '#34d399',
  cloud_devops: '#64748b',
  aws: '#ff9900',
  azure: '#0078d4',
  iam: '#4f46e5',
  cloud_security: '#0f766e',
  networking: '#2563eb',
  cost_optimization: '#ca8a04',
  security: '#dc2626',
  threat_detection: '#b91c1c',
  incident_response: '#ea580c',
  vulnerability_management: '#be123c',
  testing: '#84cc16',
  automation_frameworks: '#22c55e',
  api_testing: '#06b6d4',
  quality_strategy: '#84cc16',
  ci_cd: '#64748b',
  kubernetes: '#326ce5',
  observability: '#0ea5e9',
  mobile_architecture: '#c084fc',
  leadership: '#f97316',
  architecture: '#818cf8',
  people_management: '#ec4899',
  hiring: '#2dd4bf',
  employee_relations: '#f59e0b',
};

export const getRoleLabel = value =>
  INTERVIEW_ROLES.find(r => r.value === value)?.label || value || 'Interview Role';

export const getExperienceLabel = value =>
  EXPERIENCE_LEVELS.find(e => e.value === value)?.label || value || 'Experience Level';

export const formatCategoryLabel = category =>
  CAT_LABELS[category] || String(category || '')
    .split('_')
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
